### PR TITLE
update 13.2 to Leap 42.1

### PR DESCRIPTION
**Pull request by ddemaio**
Changed the suse-version and added descriptions for the new release.

### CODE REVIEW

**Comment by jreidinger** [comment]
thanks for fix

**Comment by coolo** [comment]
Josef, can you please make sure there is a SR to leap with these changes? it's kind of important

**Comment by jreidinger** [comment]
@coolo it should vbe already created according to jenkins:

osc -A 'https://api.opensuse.org/' cat 'openSUSE:Factory' 'yast2-slide-show' 'yast2-slide-show.spec' > /tmp/yast-rake20150916-7828-1ev44gp
yes | osc -A 'https://api.opensuse.org/' submitreq --no-cleanup 'YaST:Head' 'yast2-slide-show' 'openSUSE:Factory' -m 'submit new version 3.1.17' --yes
created request id 331390

let me check what happens

**Comment by jreidinger** [comment]
BTW I missing version bump, so if change is not in factory then please add entry to changelog and increase version of package. But from diff of https://build.opensuse.org/request/show/331390 it looks like it should be already in Leap.

**Comment by jreidinger** [comment]
ah, not leap, only factory. Will create SR to leap

**Comment by jreidinger** [comment]
@coolo done with few others: created request id 333705

**Pull request merged**
